<?php
namespace axenox\Microsoft365Connector\DataConnectors;

use exface\Core\DataConnectors\SmtpConnector;
use Symfony\Component\Mailer\Transport\TransportInterface;
use Vitrus\SymfonyOfficeGraphMailer\Transport\GraphApiTransportFactory;

/**
 * Connector to send emails through the Microsoft Graph API
 * 
 * Example config:
 * 
 * ```
 * {
 *  "tenant": "f2e8795a-4da8-755a-4d23-4a248155d752",
 *  "client_id": "f2e8795a-4da8-755a-4d23-4a248155d752",
 *  "client_secret": "Ad4Q~hHJDNpDVJMHUEIUA84457BBDbs45448DCr",
 *  "from": "no-reply@mydomain.com"
 * }
 * 
 * ```
 */
class AzureGraphApiEmailConnector extends SmtpConnector
{
    /**
     *
     * @return TransportInterface
     */
    protected function getTransport() : TransportInterface
    {
        $transport = (new GraphApiTransportFactory())->create($this->getDsn());
        return $transport;
    }

    /**
     *
     * @return string
     */
    protected function getScheme() : string
    {
        return 'microsoft-graph-api';
    }

    /**
     * Azure client id (also called application id)
     * 
     * @uxon-property client_id
     * @uxon-type string
     * 
     * @param string $clientId
     * @return AzureGraphApiEmailConnector
     */
    protected function setClientId(string $clientId) : AzureGraphApiEmailConnector
    {
        return parent::setUser($clientId);
    }

    /**
     * Azure client secret
     *
     * @uxon-property client_secret
     * @uxon-type string
     *
     * @param string $secret
     * @return AzureGraphApiEmailConnector
     */
    protected function setClientSecret(string $secret) : AzureGraphApiEmailConnector
    {
        return parent::setPassword($secret);
    }

    /**
     * Azure tenant
     *
     * @uxon-property tenant
     * @uxon-type string
     *
     * @param string $tenant
     * @return AzureGraphApiEmailConnector
     */
    protected function setTenant(string $tenant) : AzureGraphApiEmailConnector
    {
        return parent::setHost($tenant);
    }

    /**
     * @deprecated Use setClientId() instead
     * 
     * @param string $value
     * @return SmtpConnector
     */
    protected function setUser(string $value): SmtpConnector
    {
        return parent::setUser($value); // TODO: Change the autogenerated stub
    }

    /**
     * @deprecated Use setClientSecret() instead
     *
     * @param string $value
     * @return SmtpConnector
     */
    protected function setPassword(string $value): SmtpConnector
    {
        return parent::setPassword($value); // TODO: Change the autogenerated stub
    }

    /**
     * @deprecated Use setTenant() instead
     *
     * @param string $value
     * @return SmtpConnector
     */
    protected function setHost(string $value): SmtpConnector
    {
        return parent::setHost($value); // TODO: Change the autogenerated stub
    }
}